### ISSUE TITLE
Relative links in README

### ISSUE THREAD

**Issue by Travis-S** [ihincks/nv-meas-code#1]
Looks like your use of relative links in the README goes against the model GitHub uses to parse the file. According to [this help article](https://help.github.com/articles/about-readmes/), GitHub apparently thinks relative links are used to link to other documents **inside the repository itself**. Hence, GitHub has linked your links for software packages to (non-existent) files in the repo.

**Comment by ihincks** [comment]
Thanks for pointing this out, I never tried actually clicking on the links :P. However, I'm confused because they didn't look relative to me -- they all started with https:// -- it seems to me like bug in the parser that doesn't allow bibliography style links to be absolute. It was fixed in #2 by making all the link addresses inline.

EDIT: (On second thought, I was just using wrong bibliography referencing syntax)

**Comment by ihincks** [comment]
(On second thought, I was just using wrong bibliography referencing syntax)
